<?php
  //猴子选大王，一群猴子编好号，由顺序从1开始选，选到n编号的猴子出局，再从它下一位开始编号。如此反复最后剩下的猴子就是大王
  //20只猴子，选到5出局
for($i=1;$i<=19;$i++){
	$arr[]=$i;
}
$i=0;
while(count($arr)>1){
   if(($i+1)%5==0){
      unset($arr[$i]);
   }else{
      array_push($arr,$arr[$i]);
	  unset($arr[$i]);
   }
   $i++;
}
print_r($arr);
?>